"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import ProgressBar from "@badrap/bar-of-progress";
// import { Router } from "next/router";

import { useEffect } from 'react'
import { usePathname, useSearchParams } from 'next/navigation'


const inter = Inter({ subsets: ["latin"] });

 
// export function NavigationEvents() {

// }

// Router.events.on('routeChangeStart', progress.start)
// Router.events.on('routeChangeComplete', progress.finish)
// Router.events.on('routeChangeError', progress.finish)
// console.log(Router.events.on() ,'asfsaf');

export const metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const pathname = usePathname()
  const searchParams = useSearchParams()
  const progress = new ProgressBar({
    size: 4,
    color: "#FE595E",
    className: "z-50",
    delay: 100,
  });
  useEffect(() => {
    const url = `${pathname}?${searchParams}`
    setTimeout(()=> {
      progress.start
    }, 100)
    // You can now use the current URL
    // ...
  }, [pathname, searchParams])
 
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
